### ISSUE TITLE
missing script: jspm

### ISSUE THREAD

**Issue by creamer** [bclozel/spring-resource-handling#11]
Sorry, my english is pool

I want try build this project 
run "SPRING_PROFILES_ACTIVE=development RESOURCES_PROJECTROOT=`pwd` ./gradlew :server:bootRun"

but, npm ERR occurred.
below text is contents of the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'jspm',
1 verbose cli   'config registries.github.auth',
1 verbose cli   'null' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose stack Error: missing script: jspm
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20
4 verbose stack     at evalmachine.<anonymous>:263:20
4 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
5 verbose cwd /Users/ruaa/dev/ruaa/spring-resource-handling-master/client
6 error Darwin 14.3.0
7 error argv "node" "/usr/local/bin/npm" "run" "jspm" "config registries.github.auth" "null"
8 error node v0.12.5
9 error npm  v2.11.2
10 error missing script: jspm
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Please, I need help

**Comment by bclozel** [comment]
Hi @creamer 
Sorry about that - I broke the local build while trying to fix things on Travis CI.
I had a local install of JSPM that was hiding the problem.

This is now fixed, let me know how it works ou for you!

**Comment by creamer** [comment]
Thank you :+1:

**Comment by xak2000** [comment]
Broken again:

```
> Building 38% > :client:jspm_install
 > spring-resource-handling@0.0.1 jspm-install C:\Users\xakep\ws\spring-resource-handling\client
> jspm install > :client:jspm_install

"jspm" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\xakep\\ws\\spring-resource-handling\\client\\.gradle\\nodejs\\node-v6.9.1-windows-x64\\bin\\node.exe" "C:\\Users\\xakep\\ws\\spring-resource-handling\\client\\.gradle\\nodejs\\node-v6.9.1-linux-x86\\lib\\node_modules\\npm\\bin\\npm-cli.js" "run" "jspm-install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! spring-resource-handling@0.0.1 jspm-install: `jspm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spring-resource-handling@0.0.1 jspm-install script 'jspm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-resource-handling package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-resource-handling
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-resource-handling
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xakep\ws\spring-resource-handling\client\npm-debug.log
:client:jspm_install FAILED
:client:jspm_install (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.611 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client:jspm_install'.
> Process 'command 'C:\Users\xakep\ws\spring-resource-handling\client\.gradle\nodejs\node-v6.9.1-windows-x64\bin\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 3.008 secs
Stopped 0 compiler daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':client:jspm_install'.] from daemon DaemonInfo{pid=7908, address=[f0567869-3a3a-4f7c-87be-7bd15bf97783 port:58820, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1481697140890, context=DefaultDaemonContext[uid=5914454a-76e8-46b2-b216-626c65686edd,javaHome=C:\Program Files\Java\jdk1.8.0_92,daemonRegistryDir=C:\Users\xakep\.gradle\daemon,pid=7908,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1251,-Duser.country=RU,-Duser.language=ru,-Duser.variant]} (build should be done).
```

Running the `npm run jspm-install` from the `client` folder works. But even after this gradle still can't build because it cannot complete the `jspm install` step.

Only after installing `jspm` globally (`npm install -g jspm`) gradle's build starts to work.
